// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eobpjeuniytcgnvhengo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvYnBqZXVuaXl0Y2dudmhlbmdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTYyODAsImV4cCI6MjA2OTczMjI4MH0.dJ9OB1UmtBmKgZtwgNa82PTGi7jiLAH5LIlCjJurAVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});